### ISSUE TITLE
Creating SubModules fails with error

### ISSUE THREAD

**Issue by rcarjan** [michaelolof/vuex-class-component#11]
Hello,

I have created two modules for my store (UserStore and AppStore), and I tried making the AppStore a submodule of UserStore, as follows:

UserStore.ts:
```
import { VuexModule, Module }         from "vuex-class-component";
import { mutation, action, getter }       from "vuex-class-component";
import axios                                        from 'axios';
import AppStore                                 from '@/stores/AppStore';

@Module({ namespacedPath: "user/" })
export default class UserStore extends VuexModule {
// ...
private app = AppStore.CreateSubModule(AppStore);
//...
}
```

AppStore.ts:
```
import { VuexModule, Module }                       from "vuex-class-component";
import { mutation, action, getter }                 from "vuex-class-component";
import axios                                        from 'axios';
import { EventForm, Person, GApiObject, Session }   from '@/interfaces';

@Module({ namespacedPath: "app/" })
export default class AppStore extends VuexModule {
//...
}
```

store.ts:
```
import Vue          from 'vue';
import Vuex         from 'vuex';
import UserStore    from '@/stores/UserStore';
import AppStore     from '@/stores/AppStore';

Vue.use(Vuex);

// Extract Vuex Modules
const UserModule = UserStore.ExtractVuexModule(UserStore);
const AppModule  = AppStore.ExtractVuexModule(UserStore);

// export default new Vuex.Store({
//     modules: {
//         UserModule,
//     }
// });

// Create store object
export const store = new Vuex.Store({
    modules: {
        UserModule,
        AppModule
    }
});

// Create and export vuex manager object
export const vxm = {
    app:  AppStore.CreateProxy(store, AppStore)   as AppStore,
    user: UserStore.CreateProxy(store, UserStore) as UserStore,
};
```

main.ts:
```
/* Import VUE stuff */
import Vue                  from 'vue';
import App                  from './App.vue';
import router               from './router';
import { store, vxm }       from './store';

// other imports..

Vue.prototype.$vxm      = vxm;

new Vue({
    router,
    store,
    render: (h) => h(App),
    created: () => {
        console.log('created.');
    }
}).$mount('#app');
```

It compiles successfully, however when I enter the web page, I get the following error:

>  module.js:72 Uncaught TypeError: Cannot assign to read only property 'app' of object '#<Object>'
>     at module.js:72
>     at Array.map (<anonymous>)
>     at s (module.js:69)
>     at Function.t.CreateProxy (module.js:23)
>     at Module.cd49 (store.ts:29)
>     at r (bootstrap:78)
>     at Object.0 (bootstrap:151)
>     at r (bootstrap:78)
>     at a (bootstrap:45)
>     at bootstrap:151

Did I do something wrong, or is there an issue with the package?

**Comment by michaelolof** [comment]
Hello.

I'm not seeing any `vuex-class-component` specific error here.
This error seems more of a Vue mounting error.

**Comment by rcarjan** [comment]
It seems to have something to do with the `Object.defineProperty` call in `function createProxy($store, cls, cachePath)` (in module.ts).
Apparently, when defining properties with `Object.defineProperty`, they are created with the _writable_ flag set to false by default. 
After editing the (already compiled) _module.js_ in my _node_modules_ folder to this:

```
Object.getOwnPropertyNames(prototype[_1._state] || {}).map(function (name) {
    Object.defineProperty(rtn, name, {
        value: prototype[_1._state][name],
        writable: true
    });
});
```
everything seems to work okay. Here is the corresponding line and file:
https://github.com/michaelolof/vuex-class-component/blob/master/src/module.ts#L48-L52

**Comment by michaelolof** [comment]
Hello.

Fix has been added https://github.com/michaelolof/vuex-class-component/blob/master/src/module.ts#L51

Please upgrade and try it out.

**Comment by rcarjan** [comment]
Aswesome. Works like a charm. Thanks a lot!
