### ISSUE TITLE
non-async @action TypeScript error

### ISSUE THREAD

**Issue by simshaun** [michaelolof/vuex-class-component#12]
![image](https://user-images.githubusercontent.com/379519/54811633-89433d00-4c5f-11e9-8242-d8e61910c3d4.png)

Error goes away when I make the method async, but I don't really want to do that.

**Comment by michaelolof** [comment]
Actions return promises. That is how `vuex` works. Using the `setCollectionFunction` the way you've done breaks how `vuex` works.

If you want to return a value that is not a promise, try using a getter.

**Comment by simshaun** [comment]
I do want to use an action, not a getter; All our business logic is in actions that determine when, and call, mutations to actually alter state. We're just not using actions (plain JS, not TS) in an async manner currently.

So, I guess to be type-safe with this lib, we'll just have to mark all action methods as async?

**Comment by michaelolof** [comment]
Please read.
https://vuex.vuejs.org/guide/actions.html#composing-actions

Actions are asynchronous by default. Thus they will always return a promise.
`vuex-class-component` actions when called will in turn call `store.dispatch(...)` which returns a promise.
Returning anything other than a promise breaks how `vuex` works.

> So, I guess to be type-safe with this lib, we'll just have to mark all action methods as async?

Yes you do.

Also marking your actions as async is not a must. It is just convenient.
This will work.
```js
@action doSomething() {
  return new Promise(resolve => resolve( 2 ) )
}
```
They don't always have to be marked async, but they must return a promise.

**Comment by simshaun** [comment]
> Please read. https://vuex.vuejs.org/guide/actions.html#composing-actions

I did read. Keyword in first sentence of that page being "Actions are **often** asynchronous". I guess I'm in a minority that doesn't often use them asynchronously. ;) 

> Returning anything other than a promise breaks how vuex works.

I'm not returning anything at all. I think that's a mixup in communication we're having here. I'm just calling mutators so they can do their thing. Essentially, what I'm doing, in plain JS land, is no different than the first example in Vuex's Actions docs. It's not returning a promise there...
![image](https://user-images.githubusercontent.com/379519/54848174-fc2bd280-4cb6-11e9-8815-5ff6f779bc56.png)

So I guess that's where I personally got confused, as Vuex seems to be ok with actions that don't return anything, per its docs, but this lib is enforcing a Promise. I'll just return an empty promise if I have to. Keep in mind, I'm rather new to TypeScript, but I feel like actions here should be ok with not returning anything at all too.

**Comment by michaelolof** [comment]
That `increment` action is actually returning a `Promise<void>` or more accurately `Promise<undefined>`

**Comment by michaelolof** [comment]
>I'm not returning anything at all. I think that's a mixup in communication we're having here.

If that's the case what is the problem?
Are you not allowed to use the async/await syntax

**Comment by simshaun** [comment]
> That `increment` action is actually returning a `Promise<void>` or more accurately `Promise<undefined>`

I'm just coming from a plain JS point-of-view where it's OK that I don't have to return anything in my actions. It looks like Vuex handles that behind the scenes at https://github.com/vuejs/vuex/blob/dev/src/store.js#L435-L437

>If that's the case what is the problem? Are you not allowed to use the async/await syntax.

We do use async/await for actions where we care about the return value or need to make sure it finished. But, a lot of our actions are simply dispatched (fire and forget). Note: We're not using actions strictly for async purposes.

Anyway, it's not a problem for me to mark actions as async to satisfy this lib's type constraints. I just thought it wasn't necessary.

**Comment by aldarund** [comment]
@michaelolof Not quite follow why actions MUST be async. Its fine to have action that isnt async and dont return any promises and it dont break how vuex work. But if you use eslint with require-await rule it will complain that async is used but inside it nothing with await. So it will produce eslint error and will either lead to eslint disable for that action or returning some empty promise, both of which isnt good solutions since its not necessary for vuex as @simshaun mentioned and referenced in code. And the docs also nowhere state that it MUST be async, only that it CAN be.
