### ISSUE TITLE
'Symbol' is undefined in IE 11

### ISSUE THREAD

**Issue by Sojaner** [michaelolof/vuex-class-component#14]
My code was working fine in IE 10 - 11 before I added `vuex-class-component` to my project.

However as soon as I added the library, the app has stopped working giving an error which reads as "'Symbol' is undefined" in IE 10 - 11.

I have tried solutions like the one [https://stackoverflow.com/questions/33828840/symbol-is-undefined-in-ie-after-using-babel](here) with no luck.

**Comment by Sojaner** [comment]
My code was working fine in IE 10 - 11 before I added `vuex-class-component` to my project.

However as soon as I added the library, the app has stopped working giving an error which reads as "'Symbol' is undefined" in IE 10 - 11.

I have tried solutions like the one [https://stackoverflow.com/questions/33828840/symbol-is-undefined-in-ie-after-using-babel](here) with no luck.

**Comment by michaelolof** [comment]
Guess symbols are not supported in IE 10 - 11 (No surprise there).

I have removed the library's dependency on Symbols. upgrade and try now.
https://github.com/michaelolof/vuex-class-component/blob/master/src/symbols.ts#L3-L14

**Comment by Sojaner** [comment]
Thanks. Will give it a try and report the result here as soon as possible.

**Comment by Sojaner** [comment]
There is now this error appearing:

> Object doesn't support property or method 'getOwnPropertyDescriptors' in module.js (135,9)

Which refers to this line of code:

> `var fields = Object.getOwnPropertyDescriptors(target.prototype);`

The problem has changed now but not solved yet.

**Comment by Sojaner** [comment]
To clarify, this is the function where the error happens (Webpack compiled because IE doesn't provide me any more information):

```JS
function Module(options) {
    if (options === void 0) { options = defaultOptions; }
    return function (target) {
        var targetInstance = new target();
        var states = Object.getOwnPropertyNames(targetInstance);
        var stateObj = {};
        if (target.prototype[_symbols__WEBPACK_IMPORTED_MODULE_1__["_map"]] === undefined)
            target.prototype[_symbols__WEBPACK_IMPORTED_MODULE_1__["_map"]] = [];
        for (var _i = 0, states_1 = states; _i < states_1.length; _i++) {
            var stateField = states_1[_i];
            // @ts-ignore
            var stateValue = targetInstance[stateField];
            if (stateValue === undefined)
                continue;
            if (subModuleObjectIsFound(stateValue)) {
                handleSubModule(target, stateField, stateValue);
                continue;
            }
            stateObj[stateField] = stateValue;
            target.prototype[_symbols__WEBPACK_IMPORTED_MODULE_1__["_map"]].push({ value: stateField, type: "state" });
        }
        target.prototype[_symbols__WEBPACK_IMPORTED_MODULE_1__["_state"]] = stateObj;
        var fields = Object.getOwnPropertyDescriptors(target.prototype);
        if (target.prototype[_symbols__WEBPACK_IMPORTED_MODULE_1__["_getters"]] === undefined)
            target.prototype[_symbols__WEBPACK_IMPORTED_MODULE_1__["_getters"]] = {};
        var _loop_1 = function (field) {
            var getterField = fields[field].get;
            if (getterField) {
                var func = function (state) {
                    return getterField.call(state);
                };
                target.prototype[_symbols__WEBPACK_IMPORTED_MODULE_1__["_getters"]][field] = func;
            }
        };
        for (var field in fields) {
            _loop_1(field);
        }
        if (options)
            target.prototype[_symbols__WEBPACK_IMPORTED_MODULE_1__["_namespacedPath"]] = options.namespacedPath;
    };
}
```

**Comment by michaelolof** [comment]
Closing this since there no further IE complaints.
