### ISSUE TITLE
Accessing store instance and other properties in getters

### ISSUE THREAD

**Issue by rollinson9** [michaelolof/vuex-class-component#26]
Hi,

I've been looking for a library like this for a while, it makes so much more sense to me! I've gone through the documentation (and tests) and I believe I should be able to access the store in getters and additional access other getters.

Apologies if I've missed a step, but I can recreate this issue with namespaced modules below.

```javascript
@Module({ namespacedPath: 'test/' })
class TestStore extends VuexModule {
  public num = 100;

  public get biggerNum() {
    return this.num * 100;
  }

  public get biggestNum() {
    console.log(this.biggerNum /* Undefined */, this.$store /* undefined */);
    return this.biggerNum * this.$store.state.globalNum * 100;
  }
}

export const store = new Vuex.Store({
  modules: {
    test: TestStore.ExtractVuexModule(TestStore),
  },
  state: {
    globalNum: 10
  },
  mutations: {},
  actions: {},
});

// This can be imported in vue components and used for type safety
export const vxm = {
  test: TestStore.CreateProxy(store, TestStore),
};

console.log(vxm.test.biggestNum);
```

Thanks!

**Comment by michaelolof** [comment]
Hello sorry for the late reply.

`this.biggerNum` is undefined because you're trying to access a getter from another getter.

Remember Vuex getters only have access to the `state` object.

**Comment by rollinson9** [comment]
Hi,

It's no problem, thank you for the reply!

I'm not sure if that's right? I've had no problem using the normal vuex way of access getters within getters. The first argument is state, but then the second argument is generally the getters object. Within namespaced modules, the 3rd and 4th argument are rootState and rootGetters

You should be able to see what I mean here: 
https://vuex.vuejs.org/guide/getters.html#property-style-access
```javascript
const store = new Vuex.Store({
  state: {
    todos: [
      { id: 1, text: '...', done: true },
      { id: 2, text: '...', done: false }
    ]
  },
  getters: {
    doneTodos: state => {
      return state.todos.filter(todo => todo.done)
    },
    doneTodosCount: (state, getters) => {
      return getters.doneTodos.length
    }
  }
})
```

https://vuex.vuejs.org/guide/modules.html#module-local-state
```javascript
const moduleA = {
  // ...
  getters: {
    sumWithRootCount (state, getters, rootState) {
      return state.count + rootState.count
    }
  }
}
```

I hope this helps to explain what I mean, if this isn't a feature you're looking to implement then please let me know.

Thank you for you help!

**Comment by DanCardin** [comment]
We've also run into this problem. We make use of the 2nd getter param fairly extensively.

Any chance you'd consider (reopening this issue, and) fixing this or accepting a PR which adds support for it?

To a lesser extend we also use rootState and rootGetters, but we could probably live without that.
