### ISSUE TITLE
mutations_cache being shared across several modules

### ISSUE THREAD

**Issue by aymasse** [michaelolof/vuex-class-component#38]
Hello,

I'm still in the process of migrating to v2, and I am encountering a strange error.
I am declaring several modules as described in the ReadMe, and trying to add all of them to my Vuex store, like so:
```typescript
export const main = new Vuex.Store({
  modules: {
    ...extractVuexModule(ModuleA),
    ...extractVuexModule(ModuleB),
    ...extractVuexModule(ModuleC),
    ...extractVuexModule(ModuleD),
  },
});

export const vxm = {
  moduleA: createProxy(main, ModuleA),
  moduleB: createProxy(main, ModuleB),
  moduleC: createProxy(main, ModuleC),
  moduleD: createProxy(main, ModuleD),
};
```

Those different modules have each their state and each one has at least one explicit mutation.
The problem is, when I am trying to access these explicit mutations through vxm, I am getting a "is not a function" error.

By investigating further, I saw that every module has the mutation of the last extracted module (Module D here).
By using Chrome debugger, I found that `VuexClass.prototype` in
Line 54 in module.ts
```typescript
VuexClass.prototype.__mutations_cache__.__explicit_mutations__ = fromPrototype.mutations.explicitMutations;
```
is shared across my modules, and thus is overridden each time a new module is registered.
The creation of the store is executing as expected, but the creation of the proxies are using this shared prototype and so are affecting the same explicit mutations to every modules.

**Comment by michaelolof** [comment]
How are you declaring your Vuex Modules

**Comment by aymasse** [comment]
Hello, thanks for your answer.

I declare a base module in a separate file like so : 
```typescript
import { createModule } from 'vuex-class-component';

const VuexModule = createModule({
  namespaced: true,
  strict: false,
});

export default VuexModule;
```

that I import in my different modules, for example:
```typescript
import VuexModule from '@/vuex/base.vuex';
import { action, mutation } from 'vuex-class-component';

export default class ModuleA extends VuexModule {
  public someProp: any = 'prop';

  @mutation public mutationA(payload: any): void {
    // code
  }

  @action public actionA(payload: any): void {
    // code
  }
}
```

**Comment by michaelolof** [comment]
Hello @aymasse

You can upgrade to the latest version and try again.

**Comment by aymasse** [comment]
Hello @michaelolof ,

Thanks the problem I had is no more.

I just have encountered other problems unrelated to this one.
I'm closing this issue and opening a PR for these problems.
