### ISSUE TITLE
State undefined with new API in Nuxt

### ISSUE THREAD

**Issue by danielroe** [michaelolof/vuex-class-component#41]
Implementing the new API, I am running into some strange problems with a virgin Nuxt install.

Accessing `$store.state` works fine. But getters don't seem to be able to access other class properties. So, for example: `$store.getters['userStore/fullname']` returns `"undefined undefined"`.

`index.ts`:
```ts
import { UserStore } from './user'
import { extractVuexModule } from 'vuex-class-component'

export const state = () => ({
  counter: 0,
})

export const modules = {
  ...extractVuexModule(UserStore),
}
```

`user.ts` has the content of the example in the README, with typos fixed.

**Comment by michaelolof** [comment]
Would you mind sharing a sample repo so I can better debug.

Thanks a lot.

**Comment by danielroe** [comment]
@michaelolof Of course. 

https://github.com/danielroe/vuex-class-component-repro

**Comment by michaelolof** [comment]
Thanks for raising it up this has been fixed in the latest push

https://github.com/michaelolof/vuex-class-component/blob/master/src/proxy.ts#L123
