### ISSUE TITLE
Namespaced modules' path broken when code is minified

### ISSUE THREAD

**Issue by aymasse** [michaelolof/vuex-class-component#43]
Hello,

While using version `2.0.4`, module declaration is kind of broken in minified code due to the path being pulled from the class' name.
Problem is, the class name is being mangled while using `vue-cli` in its default configuration.

The result (for me) is that my store only has a single module (named `t` in my output), even if I declare several modules. This single module contains every `state property` of my modules but only the `mutations` and `actions` of the last declared one.

**Comment by SaphuA** [comment]
For now define your stores the old way:

```ts
@Module({ namespacedPath: "foo" })
export default class Foo extends VuexModule { }
```

You can still define your store the new way:

```ts
import FooStore from "@/foo/store";
const modules = { ...extractVuexModule(FooStore) };
export const store = new Vuex.Store({ modules });
```

**Comment by danielroe** [comment]
I've closed #42 as it's another expression of this issue - thanks to @SaphuA for the workaround.

If it's useful, see see [my repro](https://github.com/danielroe/vuex-class-component-repro) - and run `yarn build && yarn start`.

**Comment by vizv** [comment]
From
https://github.com/michaelolof/vuex-class-component/blob/24ed31b84f5a62bbecd0bf06202eed9a9ccc526a/src/module.ts#L89

I think you setting `namespaced` to a string should work.

```
const VuexModule = createModule({
  namespaced: 'foo',
  strict: false,
  target: "nuxt",
})
```

**Comment by michaelolof** [comment]
Hello @aymasse 

I've made an update based on the issue raised.
Thanks to @vizv 's suggestion

```ts
interface VuexModuleOptions {
  namespaced ?:string;
  ...
}
```
I've modified the `namespaced` option to take only a string.

**Comment by SaphuA** [comment]
works perfectly now
