### ISSUE TITLE
Using vuex manager inside template

### ISSUE THREAD

**Issue by SaphuA** [michaelolof/vuex-class-component#5]
I know you're not a fan of using .vue files, but that is not something I will be able to refactor away anytime soon...

I am wondering if there's a way to use the vxm directly inside my templates without the need for getters.

So instead of doing this:

```js
<template>
  <div>
    {{foo}}
  </div>
</template>

import { vxm } from './store';

@Component
export default class extends Vue {
  get foo() { return vxm.athena.foo; }
}
```

I can do this instead:
```js
<template>
  <div>
    {{vxm.athena.foo}}
  </div>
</template>

import { vxm } from './store';

@Component
export default class extends Vue {
}
```

**Comment by michaelolof** [comment]
Hmnn.

I don't think this is possible with the current way vue and vxm is used.

When you think about it the, the javascript bindings on the template all depend on the Component instance You can't do JavaScript template binding in isolation. (i.e. If it is not on the component you can't bind on it in your templates) That is just how vue works and your sample breaks that.

You could try:
```html
<template>
  <div>
    {{ vxm.athena.foo }}
  </div>
</template>

<script>
import { vxm } from "./store";

@Component
export default class extends Vue {
  // Not sure about this line.
   vxm = vxm
}
</script>
```

Or you could research into Vue Plugins and turn the vxm object into a plugin that is available in all your Vue components. sort of like how the store objects is.

Note the above example is not tested. It's just a guess from me.

**Comment by SaphuA** [comment]
Cool, that works!
