### ISSUE TITLE
Namespaced modules still broken

### ISSUE THREAD

**Issue by SaphuA** [michaelolof/vuex-class-component#52]
Okay so I was a little too optimistic when I said your last commit fixed the namespace issues. It seems that only the namespace is used of the last store that is touched or used and therefore only this store is working (which was the only page I was testing at the time...).

I'll look into it and update this issue accordingly.

**Comment by SaphuA** [comment]
```ts
export class StoreA extends createModule({ namespaced: "StoreA", strict: true }) { }
export class StoreB extends createModule({ namespaced: "StoreB", strict: true }) { }
console.log(extractVuexModule(StoreA));
console.log(extractVuexModule(StoreB));
```

prints
```
{StoreB: {…}}
{StoreB: {…}}
```

**Comment by SaphuA** [comment]
I'm pretty sure this is because all Modules share the same prototype and it's overwriting the namespace every time here:

https://github.com/michaelolof/vuex-class-component/blob/a374852288de1f5454755123215c5f115bfb9a4f/src/module.ts#L26

**Comment by SaphuA** [comment]
Could it be that the cause is that prototype is always `VuexModule` so setting `cls.prototype.__namespacedPath__ changes` it for all modules?

**Comment by michaelolof** [comment]
Mind sharing a sample project so I can replicate your issue.

Thanks

**Comment by SaphuA** [comment]
here you go

https://github.com/SaphuA/vuex-class-component-ns-repro

**Comment by michaelolof** [comment]
This issue has been resolved in the latest version

**Comment by SaphuA** [comment]
Look ok! I'll do some more testing this week.

**Comment by SaphuA** [comment]
So when exactly should one use `createModule` and when `With` for providing options?

**Comment by michaelolof** [comment]
With is useful for extending already defined options.

Ideally you want to create a base configuration like so:

```ts
const VuexModule = createModule({
  strict: false,
  target: "nuxt",
  enableLocalWatchers: true,
})

export class UserStore extends VuexModule.With({ namespaced: "user", strict: true }) {
}
```
Think of it as a 2 level inheritance for your module options.
