### ISSUE TITLE
Namespaced modules use bad action and mutation names

### ISSUE THREAD

**Issue by guyguy2001** [michaelolof/vuex-class-component#58]
I'm trying to use actions and mutations inside a namespaced module, but it seems it uses `userStore/` in both the module name and the local mutation/action name.

![image](https://user-images.githubusercontent.com/6932278/70739313-36df0a80-1d1f-11ea-8cf2-2af3b8c19584.png)

![image](https://user-images.githubusercontent.com/6932278/70739241-11520100-1d1f-11ea-804f-f452327c774e.png)

Reproduction (from which the screenshots are taken): https://github.com/guyguy2001/vuex-class-comp-repro
Am I doing something wrong? Or is this a bug?

**Comment by Velua** [comment]
Are you able to pass params to your actions via $store.dispatch? Just wondering if there's an overlap with a problem I'm facing.

**Comment by luxaritas** [comment]
This is the same issue as #55

**Comment by grandmasteralexandr** [comment]
I hava the same problem, please fix it

**Comment by tiagoroldao** [comment]
I have a PR for this fix up. In the meantime, I've been using my fork of the lib, by targeting a built commit, as such:
```
// package.lock dependencies
...
"vuex-class-component": "git+https://github.com/tiagoroldao/vuex-class-component.git#439da9698f189274cf508ad83243cc1ac3bded48",
...
```

**Comment by ivangsa** [comment]
I can confirm that linked PR fixed this issue for me..
Thanks @tiagoroldao

**Comment by LittleFox94** [comment]
I have the same problem as @guyguy2001 and the linked PR does not seem to help

**Comment by tiagoroldao** [comment]
@LittleFox94 feel free to give details to see what might be up there (potentially on  the [forked repo](https://github.com/tiagoroldao/vuex-class-component), or on the pull request I have up, #64 )

By coincidence, on another issue for this project, someone has just now pointed me to an alternative that might be worth checking out: https://github.com/paleo/direct-vuex
