### ISSUE TITLE
getter functions can't contain payload

### ISSUE THREAD

**Issue by bumpety** [michaelolof/vuex-class-component#7]
Hy, I wonder how I can create a getter function which can contain any parameters. If I create a function and add the @getter decorator like @getter foo(id: number) {..} i throws an webpack error inside the browser. Here is the error: __WEBPACK_IMPORTED_MODULE_2__store__.b.testStore.foo is not a function

**Comment by michaelolof** [comment]
The way to define getters in vuex-class-component is by using class getters.
The `@getter` decorator is useful for when you want to automatically make a `state` available as a `getter` without having to redefine it. It is not for explicitly defining getters.

```ts
get foo(id:number) {
 ...
}
```
