### ISSUE TITLE
[BUG] npm package Version 2.3.2 still has pr #64 related issues.

### ISSUE THREAD

**Issue by zhyy2008z** [michaelolof/vuex-class-component#71]
I download your lastest 2.3.2 package version from npm, it still has pr #64 related issues. But when I download your source code from your master repository directly and compile to js, it is ok, no those issues. So, I think your npm package was compiled from old source code version. Please update your npm package, thanks a lot! Please forgive my poor english!

**Comment by onkarj422** [comment]
Can't use it because of this one. Anybody up for the fix? Great library otherwise.

**Comment by tiagoroldao** [comment]
The build scripts were not updated after the PR - I'm unsure whether it was expected of a PR to include built scripts (although it should not, for [security reasons](https://www.zdnet.com/article/microsoft-spots-malicious-npm-package-stealing-data-from-unix-systems/).
