### ISSUE TITLE
[BUG]Mutation in Action doesn't work sometimes.

### ISSUE THREAD

**Issue by Freeesia** [michaelolof/vuex-class-component#74]
If I try to call Mutation through setter in Action with the following code, I may get the error.
```ts
const VuexModule = createModule({
  namespaced: "auth",
  strict: false,
});

export default class Auth extends VuexModule {
  private _user: User | null = null;

  get user() {
    return this._user;
  }

  set user(v: User | null) {
    this._user = v;
  }

  @action
  async isSignedIn() {
    let user = this.user;
    if (!user) {
      user = await getUser();
      this.user = user; // `$store.commit is not a function` error
    }
    return user ? true : false;
  }
}
```
There is a procedure that always occurs in my app, but the conditions are unknown.

When the error occurs, the $store in proxy.js:379:50 looks like this
```
$store: {
  user: null,
  __auth_internal_getter__: function,
  __auth_internal_mutator__: function,
  __proto__: Object
}
```

Thanks for your help.

**Comment by tiagoroldao** [comment]
This may have been fixed already, but built code not updated.

Try the patch detailed here, meanwhile: https://github.com/michaelolof/vuex-class-component/issues/58#issuecomment-615917529

**Comment by Freeesia** [comment]
Thank you!
I have confirmed that it has been fixed.
