### ISSUE TITLE
module inheritance

### ISSUE THREAD

**Issue by danieleades** [michaelolof/vuex-class-component#8]
Is it possible to use inheritance to extend module classes defined this way?

My use case is the following-
- define a 'service' module, which is generic over a type T and exposes CRUD methods
- extend that to concrete classes for the different types of objects in my apps

the derived classes will each need to override some methods defined in the base class, as well as add a few extra methods unique to each 'service'.

I've been trying to do this with https://championswimmer.in/vuex-module-decorators/
but it doesn't work. Or possibly it does, but only at runtime, so the compiler complains.

**Comment by michaelolof** [comment]
Interesting. I'm not sure if deep nested inheritance is a feature I actually want to add though or encourage. 

With the current vuex-class-component API, how would you expect the inheritance model to work?

**Comment by danieleades** [comment]
> Interesting. I'm not sure if deep nested inheritance is a feature I actually want to add though or encourage.
I wouldn't describe it as "deep" inheritance exactly. I need about 5 services with similar (but not identical) functionailty. Each will be responsible for serving a different object. It would be a matter of a concrete base class generic over some type T, and then concrete derived classes that add one or two methods, and override one or two others
> With the current vuex-class-component API, how would you expect the inheritance model to work?
That is precisely my question!

In all honesty it doesn't need to be inheritance that solves my problem. Philosophically i'd probably prefer composition.  How would you suggest that i reuse code between largely similar modules within the current API?

**Comment by michaelolof** [comment]
With the way vuex-class-components work inheritance is not feasible. This is because the class syntax is just a wrapper. In reality you're still using objects since that is what Vuex understands.

You could try using this pattern though. It doesn't rely on inheritance.
```ts
// concrete-service.ts
import { Module, VuexModule, action } from "vuex-class-component";

interface MyService{
  first:string;
  second:number;
}

class Service<T> {
  constructor(public service:T) {}

  doSomething() {
    return this.service;
  }
}

@Module({namespacedPath: 'myService/'})
export class ConcreteService extends VuexModule {

  private service = new Service<MyService>({ first: "One", second: 2 });

  @action() 
  async doSomething() {
    return this.service.doSomething();
  }

}
```

Then in your store:
```ts
// store.ts
import Vue from 'vue'
import Vuex from 'vuex'
import { ConcreteService } from './vuex/ConcreteService.vuex';

Vue.use(Vuex)

export const store = new Vuex.Store({
  modules: {
    myService: ConcreteService.ExtractVuexModule( ConcreteService ),
  },
})


export const vxm = {
  myService: ConcreteService.CreateProxy( store, ConcreteService ),
}
```

Please note that the way you're currently using the api itself (asides the inheritance thing) is wrong. the  `namespacedPath` value **MUST** correspond with the modules key as seen in the above snippet.

Goodluck.

**Comment by danieleades** [comment]
That's not a bad shout. Thanks for taking the time!

I still have to forward all the methods, but it would cut down a lot of boilerplate

How nicely does your API play with mixins? Could that be an avenue for code reuse?

**Comment by michaelolof** [comment]
If the mixin doesn't depend on inheritance, it should work.

**Comment by danieleades** [comment]
Closing. Supporting inheritance or mixins is clearly outside the scope of the current implementation.

The above composition strategy is a decent solution for supporting code reuse between similar modules.

Thankyou!
